//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
import { InjectionToken } from '@angular/core';
import { AuthenticationProviderInterface } from '@src/app/core/auth/authentication-provider.interface';

export interface AuthenticationProviderFactoryInterface {
    createAuthProvider(type: string, settings: any): AuthenticationProviderInterface;
}

export const AUTHENTICATION_PROVIDER_FACTORIES = new InjectionToken<AuthenticationProviderFactoryInterface[]>('AuthenticationProviderFactories');
