//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
import { Injectable } from '@angular/core';
import { LocalStorageService } from '@src/app/core/local-storage.service';

const KEY = 'USER_ROLES';

@Injectable()
export class RoleService {
    constructor(private storageService: LocalStorageService) {
    }

    getRoles(): string[] {
        return this.storageService.getItem(KEY);
    }

    setRoles(roles: string[]): void {
        this.storageService.setItem(KEY, roles);
    }

    clearRoles(): void {
        this.storageService.removeItem(KEY);
    }
}
