//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// You can write your custom code in the app-layout.config.ts file instead.
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LayoutModule } from '@progress/kendo-angular-layout';
import { SharedModule } from '@src/app/shared/shared.module';
import { AppLayoutViewBaseComponent } from '@src/app/modules/system/app-layout/app-layout.base.component';
import { AppLayoutViewComponent } from '@src/app/modules/system/app-layout/app-layout.component';
import { RouterModule } from '@angular/router';
import { NotificationComponent } from '@src/app/core/notification/notification.component';
import { KsToNotificationIconPipe } from '@src/app/core/notification/to-notification-icon.pipe';

import { config, transformConfig } from '@src/app/modules/system/app-layout/app-layout.config';

const configMeta: NgModule = {
    providers: [...config.providers],
    declarations: [
        AppLayoutViewBaseComponent,
        AppLayoutViewComponent,
        NotificationComponent,
        KsToNotificationIconPipe,
        ...config.declarations
    ],
    imports: [CommonModule, SharedModule, LayoutModule, RouterModule, ...config.imports],
    exports: [NotificationComponent, AppLayoutViewComponent, ...config.exports],
    entryComponents: [...config.entryComponents],
    bootstrap: [...config.bootstrap],
    schemas: [...config.schemas],
    id: config.id,
    jit: config.jit
};

transformConfig(configMeta);

@NgModule(configMeta)
export class AppLayoutViewModule {}
