//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// You can write your custom code in the chat.component.tns.ts file instead.
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
import { Component, Injector } from '@angular/core';

@Component({
    templateUrl: './chat.component.html',
    styleUrls: ['./chat.component.css']
})
export class ChatViewBaseComponent {
    public config = {
        chat: {
            botId: '5c793500b6b08453257802ff',
            channelId: '4658f770-d3af-405f-bfb0-8c2f1b1e948b',
            channelToken: '95765cdf-6afb-4cf2-8050-2bf1d718e005'
        }
    };

    constructor(public injector: Injector) {}
}
