//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
import { Component, Input, ViewChild, ElementRef } from '@angular/core';

@Component({
    selector: 'ks-button',
    templateUrl: './button.component.html',
})
export class KsButtonComponent {
    @ViewChild('button') public button: ElementRef;

    @Input() public config: any;
}
