//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
import { Injectable } from '@angular/core';

@Injectable()
export class StringUtilsService {
    interpolate(template: string, params: { [key: string]: any }) {
        const names = Object.keys(params);
        const values = Object.values(params);

        return new Function(...names, `return \`${template}\`;`)(...values);
    }
}
