//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
import { Component, Input, forwardRef } from '@angular/core';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';

@Component({
    selector: 'ks-form-button',
    templateUrl: './form-button.component.html',
    providers: [
        {
            provide: NG_VALUE_ACCESSOR,
            useExisting: forwardRef(() => KSFormButtonComponent),
            multi: true
        }
    ]
})
export class KSFormButtonComponent implements ControlValueAccessor {
    private onChange = (_: any) => { };

    @Input() buttonType: string;
    @Input() value: any;

    classList: string = '';

    onTap() {
        this.onChange(this.value);
    }

    writeValue(value: any): void {
        this.classList = this.value === value ? '-selected' : '';
    }

    registerOnChange(fn: any): void {
        this.onChange = fn;
    }

    registerOnTouched(): void {}
}
