//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// You can write your custom code in the unauthorized-page.config.ts file instead.
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { LayoutModule } from '@progress/kendo-angular-layout';
import { SharedModule } from '@src/app/shared/shared.module';
import { UnauthorizedPageViewBaseComponent } from '@src/app/modules/system/unauthorized-page/unauthorized-page.base.component';
import { UnauthorizedPageViewComponent } from '@src/app/modules/system/unauthorized-page/unauthorized-page.component';
import { RouterModule } from '@angular/router';

import { BottomSectionComponent } from '@src/app/modules/system/unauthorized-page/bottom-section.component';
import { TopSectionComponent } from '@src/app/modules/system/unauthorized-page/top-section.component';

import { config, transformConfig } from '@src/app/modules/system/unauthorized-page/unauthorized-page.config';

const configMeta: NgModule = {
    providers: [...config.providers],
    declarations: [
        UnauthorizedPageViewBaseComponent,
        UnauthorizedPageViewComponent,
        BottomSectionComponent,
        TopSectionComponent,
        ...config.declarations
    ],
    imports: [CommonModule, SharedModule, LayoutModule, RouterModule, ...config.imports],
    exports: [BottomSectionComponent, TopSectionComponent, ...config.exports],
    entryComponents: [...config.entryComponents],
    bootstrap: [...config.bootstrap],
    schemas: [...config.schemas],
    id: config.id,
    jit: config.jit
};

transformConfig(configMeta);

@NgModule(configMeta)
export class UnauthorizedPageViewModule {}
