//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
import { SortDescriptor } from '@src/app/core/data/state/sort-descriptor.interface';
import { CompositeFilterDescriptor } from '@src/app/core/data/state/filter-descriptor.interface';
import { GroupDescriptor } from '@src/app/core/data/grouping/group-descriptor.interface';
import { BoxLocationQuery } from '@src/app/core/data/state/box-location-query.interface';

export interface CollectionState {
    skip?: number;
    take?: number;
    sort?: Array<SortDescriptor>;
    filter?: CompositeFilterDescriptor;
    group?: Array<GroupDescriptor>;
    withinBox?: BoxLocationQuery;
}
