//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
export interface FilterDescriptor {
    field?: string | Function;
    operator: string | Function;
    value?: any;
    ignoreCase?: boolean;
}

export interface CompositeFilterDescriptor {
    logic: 'or' | 'and';
    filters: Array<FilterDescriptor | CompositeFilterDescriptor>;
}

export const isCompositeFilterDescriptor = source => source.filters !== null && source.filters !== undefined;
