//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
import { Directive, OnInit } from "@angular/core";
import { Page } from "tns-core-modules/ui/page/page";

@Directive({
    selector: "[ksShowNavBar]"
})
export class ShowNavBarDirective implements OnInit {
    constructor(private page: Page) {
    }

    ngOnInit() {
        this.page.actionBarHidden = false;
    }
}