//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
import { AggregateDescriptor, AggregateResult } from '@src/app/core/data/grouping/aggregate-descriptor.interface';

export interface GroupDescriptor {
    field: string;
    dir?: 'asc' | 'desc';
    aggregates?: Array<AggregateDescriptor>;
}

export interface GroupResult {
    items: Object[];
    aggregates: AggregateResult;
    field: string;
    value: any;
}
