//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
import { Component, ViewChild, Input, EventEmitter, Output } from '@angular/core';
import { KsNumericInputBaseComponent } from '@src/app/shared/components/numeric-input.base.component';
import { SliderComponent } from '@progress/kendo-angular-inputs';

@Component({
    selector: 'ks-slider',
    templateUrl: './slider.component.html',
})
export class KsSliderComponent extends KsNumericInputBaseComponent {
    @ViewChild('slider') public slider: SliderComponent;

    public shouldValidateComponent(): boolean {
        return false;
    }
}
