//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { GridModule } from '@progress/kendo-angular-grid';
import { IntlModule } from '@progress/kendo-angular-intl';
import { InputsModule } from '@progress/kendo-angular-inputs';
import { DateInputsModule } from '@progress/kendo-angular-dateinputs';
import { ButtonsModule } from '@progress/kendo-angular-buttons';
import { DropDownsModule } from '@progress/kendo-angular-dropdowns';
import { ChartsModule } from '@progress/kendo-angular-charts';
import { GaugesModule } from '@progress/kendo-angular-gauges';
import { LabelModule } from '@progress/kendo-angular-label';
import { LayoutModule } from '@progress/kendo-angular-layout';
import { DialogsModule } from '@progress/kendo-angular-dialog';
import { RippleModule } from '@progress/kendo-angular-ripple';
import { KsDataFormComponent } from '@src/app/shared/components/data-form/data-form.component';
import { KsDataPanelComponent } from '@src/app/shared/components/data-panel/data-panel.component';
import { KsGridComponent } from '@src/app/shared/components/grid/grid.component';
import { KsAutoCompleteComponent } from '@src/app/shared/components/auto-complete/auto-complete.component';
import { KsNumericTextBoxComponent } from '@src/app/shared/components/numeric-text-box/numeric-text-box.component';
import { KsTextBoxComponent } from '@src/app/shared/components/text-box/text-box.component';
import { KsDisabledTextBoxComponent } from '@src/app/shared/components/disabled-text-box/disabled-text-box.component';
import { KsEmailTextBoxComponent } from '@src/app/shared/components/email-text-box/email-text-box.component';
import { KsImageComponent } from '@src/app/shared/components/image/image.component';
import { KsPasswordTextBoxComponent } from '@src/app/shared/components/password-text-box/password-text-box.component';
import { KsTextAreaComponent } from '@src/app/shared/components/text-area/text-area.component';
import { KsUrlTextBoxComponent } from '@src/app/shared/components/url-text-box/url-text-box.component';
import { KsCurrencyTextBoxComponent } from '@src/app/shared/components/currency-text-box/currency-text-box.component';
import { KsSliderComponent } from '@src/app/shared/components/slider/slider.component';
import { KsMaskedTextBoxComponent } from '@src/app/shared/components/masked-text-box/masked-text-box.component';
import { KsPhoneTextBoxComponent } from '@src/app/shared/components/phone-text-box/phone-text-box.component';
import { KsIntegerTextBoxComponent } from '@src/app/shared/components/integer-text-box/integer-text-box.component';
import { KsPercentTextBoxComponent } from '@src/app/shared/components/percent-text-box/percent-text-box.component';
import { KsPercentValueTextBoxComponent } from '@src/app/shared/components/percent-value-text-box/percent-value-text-box.component';
import { KsLabelComponent } from '@src/app/shared/components/label/label.component';
import { KsCheckBoxComponent } from '@src/app/shared/components/check-box/check-box.component';
import { KsButtonComponent } from '@src/app/shared/components/button/button.component';
import { KsRadioButtonListComponent } from '@src/app/shared/components/radio-button-list/radio-button-list.component';
import { KsBooleanRadioButtonListComponent } from '@src/app/shared/components/boolean-radio-button-list/boolean-radio-button-list.component';
import { KsCalendarComponent } from '@src/app/shared/components/calendar/calendar.component';
import { KsDatePickerComponent } from '@src/app/shared/components/date-picker/date-picker.component';
import { KsTimePickerComponent } from '@src/app/shared/components/time-picker/time-picker.component';
import { KsDateTimePickerComponent } from '@src/app/shared/components/date-time-picker/date-time-picker.component';
import { KsDropDownListComponent } from '@src/app/shared/components/drop-down-list/drop-down-list.component';
import { KsCustomHtmlComponent } from '@src/app/shared/components/custom-html/custom-html.component';
import { KsTabStripComponent } from '@src/app/shared/components/tab-strip/tab-strip.component';
import { KsComboBoxComponent } from '@src/app/shared/components/combo-box/combo-box.component';
import { KsAreaChartsComponent } from '@src/app/shared/components/area-charts/area-charts.component';
import { KsBarChartsComponent } from '@src/app/shared/components/bar-charts/bar-charts.component';
import { KsLineChartsComponent } from '@src/app/shared/components/line-charts/line-charts.component';
import { KsDonutChartsComponent } from '@src/app/shared/components/donut-charts/donut-charts.component';
import { KsPieChartsComponent } from '@src/app/shared/components/pie-charts/pie-charts.component';
import { KsLanguagesDropDownComponent } from '@src/app/shared/components/languages-drop-down/languages-drop-down.component';
import { KsExpanderComponent } from '@src/app/shared/components/expander/expander.component';
import { ValidationService } from '@src/app/shared/services/validation.service';
import { ShowForRolesDirective } from '@src/app/shared/directives/show-for-roles.directive';
import { FormatValuePipe } from '@src/app/shared/pipes/format-value.pipe';
import { KsNavigationPanelBarComponent } from '@src/app/shared/components/navigation-panel-bar/navigation-panel-bar.component';
import { KsUserDropDownComponent } from '@src/app/shared/components/user-drop-down/user-drop-down.component';
import { ChatComponent } from '@src/app/shared/components/chat/chat.component';

import '@progress/kendo-angular-intl/locales/af/all';
import '@progress/kendo-angular-intl/locales/am/all';
import '@progress/kendo-angular-intl/locales/ar/all';
import '@progress/kendo-angular-intl/locales/az/all';
import '@progress/kendo-angular-intl/locales/be/all';
import '@progress/kendo-angular-intl/locales/bg/all';
import '@progress/kendo-angular-intl/locales/bn/all';
import '@progress/kendo-angular-intl/locales/bs/all';
import '@progress/kendo-angular-intl/locales/ca/all';
import '@progress/kendo-angular-intl/locales/de/all';
import '@progress/kendo-angular-intl/locales/en/all';
import '@progress/kendo-angular-intl/locales/el/all';
import '@progress/kendo-angular-intl/locales/es/all';
import '@progress/kendo-angular-intl/locales/fr/all';
import '@progress/kendo-angular-intl/locales/it/all';
import '@progress/kendo-angular-intl/locales/ja/all';
import '@progress/kendo-angular-intl/locales/pt/all';
import '@progress/kendo-angular-intl/locales/ru/all';
import '@progress/kendo-angular-intl/locales/tr/all';

import 'hammerjs';

import { config, transformConfig } from '@src/app/shared/shared.config';

const configMeta: NgModule = {
    providers: [
        ValidationService,
        ...config.providers
    ],
    declarations: [
        KsTextBoxComponent,
        KsDataFormComponent,
        KsDataPanelComponent,
        KsGridComponent,
        KsAutoCompleteComponent,
        KsNumericTextBoxComponent,
        KsCurrencyTextBoxComponent,
        KsIntegerTextBoxComponent,
        KsPercentTextBoxComponent,
        KsPercentValueTextBoxComponent,
        KsDisabledTextBoxComponent,
        KsEmailTextBoxComponent,
        KsImageComponent,
        KsPasswordTextBoxComponent,
        KsTextAreaComponent,
        KsUrlTextBoxComponent,
        KsLabelComponent,
        KsCheckBoxComponent,
        KsButtonComponent,
        KsMaskedTextBoxComponent,
        KsPhoneTextBoxComponent,
        KsRadioButtonListComponent,
        KsBooleanRadioButtonListComponent,
        KsSliderComponent,
        KsCalendarComponent,
        KsDatePickerComponent,
        KsTimePickerComponent,
        KsDateTimePickerComponent,
        KsDropDownListComponent,
        KsCustomHtmlComponent,
        KsTabStripComponent,
        KsComboBoxComponent,
        KsExpanderComponent,
        KsAreaChartsComponent,
        KsBarChartsComponent,
        KsLineChartsComponent,
        KsDonutChartsComponent,
        KsPieChartsComponent,
        KsLanguagesDropDownComponent,
        KsNavigationPanelBarComponent,
        KsUserDropDownComponent,
        ShowForRolesDirective,
        FormatValuePipe,
        ChatComponent,
        ...config.declarations
    ],
    imports: [
        CommonModule,
        GridModule,
        TranslateModule,
        ReactiveFormsModule,
        FormsModule,
        IntlModule,
        InputsModule,
        ButtonsModule,
        DateInputsModule,
        DropDownsModule,
        ChartsModule,
        GaugesModule,
        LabelModule,
        LayoutModule,
        DialogsModule,
        RippleModule,
        RouterModule,
        ...config.imports
    ],
    exports: [
        FormsModule,
        ReactiveFormsModule,
        GridModule,
        IntlModule,
        InputsModule,
        DateInputsModule,
        ButtonsModule,
        DropDownsModule,
        ChartsModule,
        GaugesModule,
        LabelModule,
        LayoutModule,
        DialogsModule,
        RippleModule,
        TranslateModule,
        KsGridComponent,
        KsTextBoxComponent,
        KsDataFormComponent,
        KsDataPanelComponent,
        KsAutoCompleteComponent,
        KsNumericTextBoxComponent,
        KsCurrencyTextBoxComponent,
        KsIntegerTextBoxComponent,
        KsPercentTextBoxComponent,
        KsPercentValueTextBoxComponent,
        KsDisabledTextBoxComponent,
        KsEmailTextBoxComponent,
        KsImageComponent,
        KsPasswordTextBoxComponent,
        KsTextAreaComponent,
        KsUrlTextBoxComponent,
        KsLabelComponent,
        KsCheckBoxComponent,
        KsButtonComponent,
        KsMaskedTextBoxComponent,
        KsPhoneTextBoxComponent,
        KsRadioButtonListComponent,
        KsBooleanRadioButtonListComponent,
        KsSliderComponent,
        KsCalendarComponent,
        KsDatePickerComponent,
        KsTimePickerComponent,
        KsDateTimePickerComponent,
        KsButtonComponent,
        KsDropDownListComponent,
        KsCustomHtmlComponent,
        KsComboBoxComponent,
        KsTabStripComponent,
        KsExpanderComponent,
        KsAreaChartsComponent,
        KsBarChartsComponent,
        KsLineChartsComponent,
        KsDonutChartsComponent,
        KsPieChartsComponent,
        KsLanguagesDropDownComponent,
        KsNavigationPanelBarComponent,
        KsUserDropDownComponent,
        ShowForRolesDirective,
        FormatValuePipe,
        ChatComponent,
        ...config.exports
    ],
    entryComponents: [
        ...config.entryComponents
    ],
    bootstrap: [
        ...config.bootstrap
    ],
    schemas: [
        ...config.schemas
    ],
    id: config.id,
    jit: config.jit
};

transformConfig(configMeta);

@NgModule(configMeta)
export class SharedModule { }
