//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { FormArray } from '@angular/forms';

@Component({
    selector: 'ks-data-form',
    templateUrl: './data-form.component.html',
})
export class KsDataFormComponent {
    private _model: any;

    @Input() public viewFormArray: FormArray;

    @Input() set model(value: any) {
        this._model = value;
    }
}
