//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
import { Component, Input, ViewChild, ElementRef } from '@angular/core';

@Component({
    selector: 'ks-expander',
    templateUrl: './expander.component.html',
})
export class KsExpanderComponent {
    @ViewChild('expanderElement') public expanderElement: ElementRef;

    @Input() public config: any;
    @Input() public id: string;
}
