//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
import { Component, Input } from '@angular/core';

@Component({
    selector: 'ks-custom-html',
    templateUrl: './custom-html.component.html',
})
export class KsCustomHtmlComponent {
    @Input() public id: string;
}
