//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
import { Component, ViewEncapsulation } from '@angular/core';

@Component({
    selector: 'app-root',
    encapsulation: ViewEncapsulation.None,
    templateUrl: './app.component.html',
    styleUrls: [
        '../assets/themes/metro.css',
        '../../node_modules/bootstrap/dist/css/bootstrap.min.css',
        '../../node_modules/font-awesome/css/font-awesome.css',
        './app.css',
        './app.custom.css',
        './kendo.overrides.css'
    ]
})
export class AppComponent {}
