//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
import { Component, Input } from '@angular/core';
import { ActivatedRoute } from '@angular/router';
import { ExtendedNavigationExtras } from 'nativescript-angular/router/router-extensions';
import { EventData } from "tns-core-modules/data/observable";
import { NavigationService } from '@src/app/core/services/navigation.service';

@Component({
    selector: 'ks-button',
    templateUrl: './button.component.html'
})
export class KSButtonComponent {
    @Input()
    public navigateTo: { module?: string; view?: string; parameter?: string; dataSourceTypeName?: string; };

    constructor(
        protected navigationService: NavigationService,
        protected activatedRoute: ActivatedRoute) { }

    public onTap(args: EventData, id?: string) {
        if (!this.navigateTo || !this.navigateTo.module || !this.navigateTo.view) {
            return;
        }

        const command = [this.navigateTo.module, this.navigateTo.view];
        const extras: ExtendedNavigationExtras = {
            relativeTo: this.activatedRoute
        };

        if (id && this.navigateTo.dataSourceTypeName) {
            extras.queryParams = {
                [`${this.navigateTo.dataSourceTypeName}Id`]: id
            };
        }

        this.navigationService.navigate(command, extras);
    }
}
