//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
import { Component, Input, ViewChild, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { PanelBarComponent } from '@progress/kendo-angular-layout';

@Component({
    selector: 'ks-navigation-panel-bar',
    templateUrl: './navigation-panel-bar.component.html',
})
export class KsNavigationPanelBarComponent implements OnInit {
    @Input() public config: any;
    @Input() public id: string;
    @Input() public navigationData: any;
    @ViewChild('nav') public nav: PanelBarComponent;

    constructor(public router: Router) {
    }

    public stateChange() {
        this.nav.contentChildItems.forEach((item, index) => {
            this.navigationData[index].expanded = item.expanded;
        });
    }

    ngOnInit() {
        document.querySelector('.ks-side-navigation').classList.remove('ks-mobile-navigation');

        this.navigationData.forEach(parentItem => {
            parentItem.children.forEach(child => {
                child.expanded = child.routerLink === this.router.url;
            });

            parentItem.expanded = parentItem.children.some(c => c.expanded);
        });
    }
}
