//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
import { Injectable } from '@angular/core';
import { environment } from '@src/environments/environment';

@Injectable()
export class DataProviderService {
    public get(providerName: string) {
        const dataProviders = environment.getDataProviders();
        return dataProviders[providerName];
    }
}
