//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
import { Injectable } from '@angular/core';
import { Observable, Subject, Subscription } from 'rxjs';

import { Notification } from '@src/app/core//notification/notification';

@Injectable()
export class NotificationService {
    private notificationsSource: Subject<Notification> = new Subject<Notification>();
    private notifications: Observable<Notification> = this.notificationsSource.asObservable();

    /**
     * Triggers the notification
     */
    public notify(notification: Notification): void {
        this.notificationsSource.next(notification);
    }

    /**
     * Subscribes to notification events
     */
    public subscribe(callback: (notification: Notification) => void): Subscription {
        return this.notifications.subscribe(callback);
    }
}
