//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
import { Pipe, PipeTransform } from '@angular/core';

@Pipe({name: 'kbToIcon'})
export class KsToNotificationIconPipe implements PipeTransform {
    public transform(value: string): string {
        const BASE_CLASS = 'k-icon';
        const PREFIX = 'k-i-';
        let iconName: string;

        switch (value) {
            case 'success':
                iconName = 'check-outline';
                break;
            case 'info':
                iconName = 'information';
                break;
            case 'error':
                iconName = 'warning';
                break;
            default:
                iconName = 'information';
        }
        return BASE_CLASS + ' ' + PREFIX + iconName;
    }
}
