//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
import { Component, ViewChild, ElementRef } from '@angular/core';
import { KsTextBoxBaseComponent } from '@src/app/shared/components/text-box.base.component';

@Component({
    selector: 'ks-text-box',
    templateUrl: './text-box.component.html',
})
export class KsTextBoxComponent extends KsTextBoxBaseComponent {
    @ViewChild('input') public input: ElementRef;
}
