//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
import { Kinvey } from 'kinvey-nativescript-sdk';

import { KinveyServiceConfig } from '@src/app/core/data/kinvey-service-config';
import { Account } from '@src/app/data/account.model';

export function getAccountConfig(): KinveyServiceConfig {
    return {
        dataProviderName: 'DefaultDataProvider',
        modelTypeName: 'Account',
        serverOperations: true,
        createModel: () => new Account(),
        collection: 'Accounts',
        dataStoreType: Kinvey.DataStoreType.Cache,
        loadOnDemand: true,
        requestOptions: {
            kinveyFileTLS: true
        }
    };
}
