//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
export class Ticket {
    public _id: string;
    public Type: string;
    public Status: string;
    public Reason: string;
    public Origin: string;
    public Subject: string;
    public Priority: string;
    public Description: string;
    public CaseNumber: string;
    public Photo: string;
    public _geoloc: Array<number>;
}
