//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
import { KinveyServiceConfig } from '@src/app/core/data/kinvey-service-config';
import { TicketPriority } from '@src/app/data/ticket-priority.model';

export function getTicketPriorityConfig(): KinveyServiceConfig {
    return {
        dataProviderName: 'DefaultDataProvider',
        modelTypeName: 'TicketPriority',
        serverOperations: true,
        createModel: () => new TicketPriority(),
        collection: 'TicketPriority'
    };
}
