//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
import { KinveyServiceConfig } from '@src/app/core/data/kinvey-service-config';
import { Ticket } from '@src/app/data/ticket.model';

export function getTicketConfig(): KinveyServiceConfig {
    return {
        dataProviderName: 'DefaultDataProvider',
        modelTypeName: 'Ticket',
        serverOperations: true,
        createModel: () => new Ticket(),
        collection: 'tickets'
    };
}
