//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
import { NgModule } from '@angular/core';
import { Routes } from '@angular/router';
import { NativeScriptRouterModule } from 'nativescript-angular/router';
import { ChatViewComponent } from '@src/app/modules/tickets/chat/chat.component';
import { ListingViewComponent } from '@src/app/modules/tickets/listing/listing.component';
import { TicketDetailsViewComponent } from '@src/app/modules/tickets/ticket-details/ticket-details.component';
import { AuthenticationGuardService } from '@src/app/core/auth/authentication-guard.service';

import { config } from '@src/app/modules/tickets/tickets-routing.config';

const routes: Routes = [
    {
        path: 'ticket-details/:id',
        canActivate: [AuthenticationGuardService],
        component: TicketDetailsViewComponent
    },
    {
        path: 'chat',
        canActivate: [AuthenticationGuardService],
        component: ChatViewComponent
    },
    {
        path: 'listing',
        canActivate: [AuthenticationGuardService],
        component: ListingViewComponent
    },
    {
        path: 'ticket-details',
        canActivate: [AuthenticationGuardService],
        component: TicketDetailsViewComponent
    },
    ...config.routes
];

@NgModule({
    imports: [NativeScriptRouterModule.forChild(routes)],
    exports: [NativeScriptRouterModule]
})
export class TicketsRoutingModule {}
