//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
// this import should be first in order to load some required settings (like globals and reflect-metadata)
import { platformNativeScriptDynamic } from 'nativescript-angular/platform';
import { registerElement } from "nativescript-angular/element-registry";
import { Kinvey } from 'kinvey-nativescript-sdk';

try {
    const mapbox = require('nativescript-mapbox');
    registerElement("Mapbox", () => mapbox.MapboxView);
} catch {
    console.log('Missing \'nativescript-mapbox\' plugin, the map component cannot be used!')
}

import { AppModule } from '@src/app/app.module';
import { init } from '@src/main.config';

Kinvey.init();
init();

// A traditional NativeScript application starts by initializing global objects, setting up global CSS rules, creating, and navigating to the main page.
// Angular applications need to take care of their own initialization: modules, components, directives, routes, DI providers.
// A NativeScript Angular app needs to make both paradigms work together, so we provide a wrapper platform object, platformNativeScriptDynamic,
// that sets up a NativeScript application and can bootstrap the Angular framework.
platformNativeScriptDynamic().bootstrapModule(AppModule);
