//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
import { enableProdMode } from '@angular/core';
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';

import { AppModule } from '@src/app/app.module';
import { environment } from '@src/environments/environment';
import { init } from '@src/main.config';
import { hmrBootstrap } from '@src/hmr';

init();

if (environment.production) {
  enableProdMode();
}
const promise = platformBrowserDynamic().bootstrapModule(AppModule);
promise.catch(err => console.log(err));
const bootstrap = () => promise;

if (environment.hmr) {
  if (module[ 'hot' ]) {
    hmrBootstrap(module, bootstrap);
  } else {
    console.error('Hot Module Replacement is not enabled for webpack');
  }
} else {
  bootstrap();
}
