//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
import { AbstractControl } from '@angular/forms';

export class CustomValidators {

    public static mailFormat(control: AbstractControl): ValidationResult {
        const EMAIL_REGEXP: RegExp = /^[a-z0-9!#$%&'*+\/=?^_`{|}~.-]+@[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)*$/i;

        if (control.value !== '' && !EMAIL_REGEXP.test(control.value)) {
            return {
                'incorrectMail': true
            };
        }

        return null;
    }

    public static urlFormat(control: AbstractControl): ValidationResult {
        const URL_REGEXP: RegExp = /((([A-Za-z]{3,9}:(?:\/\/)?)(?:[-;:&=\+\$,\w]+@)?[A-Za-z0-9.-]+|(?:www.|[-;:&=\+\$,\w]+@)[A-Za-z0-9.-]+)((?:\/[\+~%\/.\w-_]*)?\??(?:[-\+=&;%@.\w_]*)#?(?:[\w]*))?)/i; /* tslint:disable-line */

        if (control.value !== '' && !URL_REGEXP.test(control.value)) {
            return {
                'invalidUrl': true
            };
        }

        return null;
    }
}

interface ValidationResult {
    [key: string]: boolean;
}
