//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
import { Input, EventEmitter, Output } from '@angular/core';
import { KsInputBaseComponent } from '@src/app/shared/components/input.base.component';

export abstract class KsDateInputBaseComponent extends KsInputBaseComponent  {
    @Output() public modelChange: EventEmitter<Date> = new EventEmitter();

    set model(value: Date) {
        super.setModel<Date>(value);
    }

    @Input() get model(): Date {
        return super.getModel<Date>();
    }

    public valueChange(value: Date): void {
        super.setModel<Date>(value);
        super.setErrorMessage();
    }

    public shouldValidateComponent(): boolean {
        return super.shouldValidateComponent() ||
            this.config.min !== undefined ||
            this.config.max !== undefined;
    }

    protected getDefaultValidationMessages(): any {
        const messages: any = super.getDefaultValidationMessages();
        messages['maxError'] = `Please enter a value less than or equal to ${this.config.max}.`;
        messages['minError'] = `Please enter a value greater than or equal to ${this.config.min}.`;

        return messages;
    }
}
