//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
import { environment } from '@src/environments/environment';

interface StorageInterface {
    getItem(key: string): string | null;
    removeItem(key: string): void;
    setItem(key: string, data: string): void;
}

export class BaseStorageService {
    protected storage: StorageInterface;

    public setItem(key: string, value: any): void {
        this.storage.setItem(this.getKey(key), JSON.stringify(value));
    }

    public getItem(key: string): any {
        return JSON.parse(this.storage.getItem(this.getKey(key)));
    }

    public removeItem(key): void {
        this.storage.removeItem(this.getKey(key));
    }

    private getKey(key: string): string {
        return `$kuib.${environment.appName}.${key}.${environment.appId}`;
    }
}
