//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
import { Injectable } from '@angular/core';

import { Observable, Subject, merge } from 'rxjs';
import { flatMap } from 'rxjs/operators';

@Injectable()
export class ErrorHandlingService {
    protected errors = new Subject<Observable<Error>>();

    constructor() {
        merge(this.errors)
            .pipe(
                flatMap(errors => errors)
            )
            .subscribe((err: any) => {
                if (err ) {
                    const message = (err.error && (err.error.message || err.error.error)) || err.message;
                    // alert(message);
                }
            });
    }

    public subscribe(errors: Observable<Error>) {
        this.errors.next(errors);
    }
}