//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
import { Injectable } from '@angular/core';

import { Observable, Subject, merge } from 'rxjs';
import { flatMap } from 'rxjs/operators';

import { Notification } from '@src/app/core/notification/notification';
import { NotificationService } from '@src/app/core/notification/notification.service';

@Injectable()
export class ErrorHandlingService {
    protected errors = new Subject<Observable<Error>>();

    constructor(protected notificationService: NotificationService) {
        merge(this.errors)
            .pipe(
                flatMap(errors => errors)
            )
            .subscribe(error => {
                if (error) {
                    this.notificationService.notify(this.createErrorNotification(error));
                }
            });
    }

    public subscribe(errors: Observable<Error>) {
        this.errors.next(errors);
    }

    protected createErrorNotification(err: any) {
        const message = (err.error && (err.error.message || err.error.error)) || err.message;
        return new Notification(`<ul><li>${message}<li></ul>`, 'error', 10000);
    }
}