//-------------------------------------------------------------------------
// <Auto-generated file - do not modify!>
//
// This code was generated automatically by Kinvey Studio.
//
// Changes to this file may cause undesired behavior and will be lost
// the next time the code regenerates.
//
// Find more information on https://devcenter.kinvey.com/guides/studio-extension-points.
//-------------------------------------------------------------------------
import { Injectable } from '@angular/core';

@Injectable()
export class SessionStorageService {
  public setItem(key: string, value: any): void {
  }

  public getItem(key: string): any {
    return {
      providerIndex: 0
    }
  }

  public removeItem(key): void {
  }
}
